services:
  - type: worker  # Измените с 'web' на 'worker' для фоновых задач
    name: ai-video-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python schedule_runner.py
    pythonVersion: 3.10.13
